### PR TITLE
Creates all the standard docs + repo integration guide

### PR DESCRIPTION
**Pull request by twof**
Resolves https://github.com/vapor/bot-github/issues/3

### CODE REVIEW

**Review by MrLotU — APPROVED** [review]
LGTM, but in the `repo_configuration_guide.md`, you might want to state a little bit clearer this is a specific setup for the Performance tests. This'll make things more clear for when we add other functions to the bots (for example the compat suite).

Might even be worth it to move them to seperate files `Docs/repo_configuration/performance.md` and `Docs/repo_configuration/compat_suite.md` or something

**Review by tanner0101 — APPROVED** [review]
really nice work on this 👍 💯

**Comment by twof** [comment]
@MrLotU I see where you're coming from, but the setup should be the same regardless. There will be some steps required to use some features and not others (eg. you won't need the CircleCI integration to use some commands), but the brunt of setup will be required for all features. I'm going to merge everything as is, and we can address your concerns if they come up.

**Comment by penny-coin** [comment]
Hey @twof, you just merged a pull request, have a coin! 

You now have 53 coins.

**Pull request merged**
